FROM vishnumohan/beakerx-dcos

ARG CONDA_ENV_YML="beakerx-root-conda-sparkmagic-env.yml"

COPY --chown="1000:100" "${CONDA_ENV_YML}" "${CONDA_DIR}/"

USER "${NB_UID}"

RUN ${CONDA_DIR}/bin/conda env update --json -q -f "${CONDA_DIR}/${CONDA_ENV_YML}" \
    && ${CONDA_DIR}/bin/conda update --json --all -yq \
    && ${CONDA_DIR}/bin/npm cache clean --force \
    && rm -rf "${CONDA_DIR}/share/jupyter/lab/staging" \
    && rm -rf "${HOME}/.cache/pip" "${HOME}/.cache/yarn" "${HOME}/.node-gyp" \
    && ${CONDA_DIR}/bin/conda clean --json -tipsy \
    && fix-permissions "${CONDA_DIR}" \
    && fix-permissions "${HOME}"
